version: '3.7'
services:
  backend:
    container_name: backend
    build:
      context: .
    ports:
      - '8080:8080'
    depends_on:
      - mysql
    environment:
      DB_ADDR: mysql:3306

  mysql:
    container_name: mysql
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: gt-online
    ports:
      - "3306:3306"
    volumes:
      - ./devstack/deployment/intidb:/docker-entrypoint-initdb.d