version: '3.7'
services:
  mysql:
    container_name: mysql
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: gt-online
    ports:
      - "3306:3306"
    volumes:
      - ./deployment/intidb:/docker-entrypoint-initdb.d